#  Program name: makefile
#  Author:       Aaron Nesbit
#  Date:         10/5/19
#  Description: makefile for CS 162 Lab 1

default:
	g++ readMatrix.cpp determinant.cpp main.cpp -o MatrixCalculator

clean:
	-rm $(objects) MatrixCalculator

