# Program name:  Project 2 (makefile)
# Author:        Aaron Nesbit
# Date:          10/21/19
# Descriptioon:  makefile for Zoo Tycoon

default:
	g++ -std=c++11 main.cpp Animal.cpp Penguin.cpp Tiger.cpp Turtle.cpp Zoo.cpp input_validation.cpp -o ZooTycoon

clean:
	-rm $(objects) ZooTycoon
