# Program name: makefile
# Author:       Aaron Nesbit
# Date:         10/18/19
# Description:  makefile for CS 162 Lab 3

default:
	g++ -std=c++11 Die.cpp Game.cpp input_validation.cpp LoadedDie.cpp main.cpp Player.cpp -o DiceWar

clean:
	-rm $(objects) DiceWar


