# Program name:  Project 1 (makefile)
# Author:        Aaron Nesbit
# Date:          10/9/19
# Description:   This is the makefile for CS 162 Project 1

default:
	g++ main.cpp menu.cpp ant.cpp board.cpp print.cpp intValidator2.cpp -o AntSimulator 

clean:
	-rm $(objects) AntSimulator

