# Program name: makefile
# Author:       Aaron Nesbit
# Date:         10/10/19
# Description:  makefile for CS 162 Lab 2

default:
	g++ -std=c++11 main.cpp count_letters.cpp output_letters.cpp arrayChecker.cpp -o LetterCounter

clean:
	-rm $(objects) LetterCounter

