# Program name: makefile
# Author:       Aaron Nesbit
# Date:         10/24/19
# Description:  makefile for CS 162 Lab 4

default:
	g++ -std=c++11 Building.cpp input_validation.cpp Instructor.cpp main.cpp Person.cpp Student.cpp University.cpp -o InfoSys

clean:
	-rm $(objects) InfoSys


