# Program name: makefile
# Author:       Aaron Nesbit
# Date:         11/22/19
# Description:  makefile for CS 162 Project 4


default:
	g++ -std=c++11 main.cpp Queue.cpp Node.cpp InputValidation.cpp Game.cpp Die.cpp Character.cpp Vampire.cpp Barbarian.cpp BlueMen.cpp Medusa.cpp HarryPotter.cpp -o Tournament

clean:
	-rm $(objects) Tournament

zip:
	zip -D Project4_Nesbit_Aaron.zip makefile main.cpp Queue.hpp Queue.cpp Node.hpp Node.cpp InputValidation.hpp InputValidation.cpp Game.hpp Game.cpp Die.hpp Die.cpp Character.hpp Character.cpp Vampire.hpp Vampire.cpp Barbarian.hpp Barbarian.cpp BlueMen.hpp BlueMen.cpp Medusa.hpp Medusa.cpp HarryPotter.hpp HarryPotter.cpp Project_4_Reflection_Report_Nesbit_Aaron.pdf
