# Program name: makefile
# Author:       Aaron Nesbit
# Date:         11/7/19
# Description:  makefile for CS 162 Project 3

default:
	g++ -std=c++11 Barbarian.cpp Blue_Men.cpp Character.cpp Game.cpp Harry_Potter.cpp input_validation.cpp main.cpp Medusa.cpp Vampire.cpp -o Fantasy

clean:
	-rm $(objects) Fantasy

zip:
	zip -D Project3_Nesbit_Aaron.zip Barbarian.hpp Barbarian.cpp Blue_Men.hpp Blue_Men.cpp Character.hpp Character.cpp Game.hpp Game.cpp Harry_Potter.hpp Harry_Potter.cpp input_validation.cpp input_validation.hpp main.cpp makefile Medusa.hpp Medusa.cpp Vampire.hpp Vampire.cpp Project_3_Reflection_Report_Nesbit_Aaron.pdf
